language: node_js
node_js:
- 8
- 6
- 5
- 4
branches:
  only:
  - master
  - /^(v\d+\.\d+(\.\d+)?)*$/
notifications:
  email: false
cache:
  directories:
    - "node_modules"
before_script:
- npm run lint
after_success:
- cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  on:
    tags: true
    node: 6
  provider: npm
  email: amsmith514@gmail.com
  api_key:
    secure: J9B5OXMpyRTcYAUsrpa5TGY0csSPQjoizs08WMBoLq52rt2Kt6FY3SNC8CORojz9VvJdKJ+hv5qw11tZv5B+lSLLHiWtLi3pDqlG3pVsMyjiwuPtU/G4c+LgCYDop9dxKHV4k7CEQXA6ekGu/sjlNqQpk/3wrf8ol7HmiGZc1N4fUCENjF7j7dXlaHeoiUkeZCRUa/1SYV9kbDScklMeQ1HoTm5mccNQahFvGgDfrdFt/Hc9JZm0IyjyOeD53ktnC4VwUYtlMxy7VQlIB1zBcI1QNGL7y3hP7guC7rwaIMCCNKySs0zy3ajQp+iUat6ONmG4dqoLlVp4hQ1c00TW3/Eb5rZI+7cEJg4sxN1ECezkU7HOUxUlSgwWFFLPaFijK2a3LGETZt6TmfKI6LFSKJgZAvx36ZRuTY1gixo43dr4K715orOb4dmFm0QanA6ko84rNfXqfrctcw1M9SHWL/BfadOzXx4UHjB0rv8Cg+viDUMMt78IOA6WALcJiudqIDSw5sFvr7z+vc4gYR+zyisZTQiNZQP9fU/kKJPBhaUjzcQth9y74Mksk/eN1Lhm9CXF0u3OHjksRCQs9sw/3kXQu5J5Y4TRUsh6XdU0xH8hj0FSOpD6elqFnnL2ITeClHEliJA4THiasGCW4vSQILBuBe5vdyAUB4gleRzmbbc=
